version: '3.8'

services:
  db:
    image: postgres:15
    container_name: subscription_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscription_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    build: .
    container_name: subscription_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=subscription_db
      - DB_SSLMODE=disable
      - SERVER_PORT=8080
    depends_on:
      - db
    restart: on-failure
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge